// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBemXZs_aBlGekEHUwkRcLakHDh5ybvUms',
    appId: '1:1087497419842:web:25083e679cd08c75e541db',
    messagingSenderId: '1087497419842',
    projectId: 'meeting-app-4e0c2',
    authDomain: 'meeting-app-4e0c2.firebaseapp.com',
    storageBucket: 'meeting-app-4e0c2.firebasestorage.app',
    measurementId: 'G-XVX031NH9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU1D_k0nYdS7xNsJUpDPrcvsoWTZKav2Y',
    appId: '1:1087497419842:android:7e28e5f369063d1ce541db',
    messagingSenderId: '1087497419842',
    projectId: 'meeting-app-4e0c2',
    storageBucket: 'meeting-app-4e0c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsiGT09yo0vRBFo4TaFwx3ESEhcL_XZ6E',
    appId: '1:1087497419842:ios:91fe556372947f26e541db',
    messagingSenderId: '1087497419842',
    projectId: 'meeting-app-4e0c2',
    storageBucket: 'meeting-app-4e0c2.firebasestorage.app',
    iosBundleId: 'com.example.meeting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsiGT09yo0vRBFo4TaFwx3ESEhcL_XZ6E',
    appId: '1:1087497419842:ios:91fe556372947f26e541db',
    messagingSenderId: '1087497419842',
    projectId: 'meeting-app-4e0c2',
    storageBucket: 'meeting-app-4e0c2.firebasestorage.app',
    iosBundleId: 'com.example.meeting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBemXZs_aBlGekEHUwkRcLakHDh5ybvUms',
    appId: '1:1087497419842:web:dce027e2b1252e3ee541db',
    messagingSenderId: '1087497419842',
    projectId: 'meeting-app-4e0c2',
    authDomain: 'meeting-app-4e0c2.firebaseapp.com',
    storageBucket: 'meeting-app-4e0c2.firebasestorage.app',
    measurementId: 'G-QQ2KLBC0MY',
  );
}
